#!/bin/bash

#If this is the first time you run the container, clone (get) PlexConnect, else update
if [ ! -f /PlexConnect/ATVSettings.cfg ]; then
  echo "*** Cloning PlexConnect ***"
  cd /
  git clone https://github.com/iBaa/PlexConnect.git
else
  echo "*** Updating PlexConnect ***"
  cd /PlexConnect
  git pull
fi

#If this is the first time, generate certificates
if [ ! -f /PlexConnect/assets/certificates/marketwatch.pem ]; then
  echo "*** Generating certificates ***"
  openssl req -new -nodes -newkey rsa:2048 -out ./marketwatch.pem -keyout ./marketwatch.key -x509 -days 7300 -subj "/C=US/CN=video-api-secure.wsj.com"
  openssl x509 -in ./marketwatch.pem -outform der -out ./marketwatch.cer && cat ./marketwatch.key >> ./marketwatch.pem
  mv marketwatch.* /PlexConnect/assets/certificates
fi

echo "*** Setting userID and groupID ***"
chown -R $USERID:$GROUPID /PlexConnect

echo "*** Starting PlexConnect ***"
python /PlexConnect/PlexConnect.py
